# -*- coding: utf-8 -*-
"""SistemasOperativosPractica1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cbj_dIhc4MeAj3lI8cTFpIfuNJkdOgXB

#Ejercicio 1
"""

import os
import sys
import time

def MostrarPCB(Pid,Etiqueta):
  Campos =[
      "Name",
      "State",
      "Pid",
      "PPid",
      "VmSize",
      "VmRss",
      "voluntary_ctxt_switches",
  ]
  print(f"Mostrandeo PCB de {Etiqueta}")
  for campo in Campos:
    with open(f"/proc/{Pid}/status") as F:
      for Linea in F:
       if Linea.startswith(campo):
          print(f"{Linea}")

print("Ejercicio 1 - Inspección de PCB de padre e hijo")
print(f"PADRE PID {os.getpid()}")
MostrarPCB(os.getpid(),"Proceso Padre")

print("Creando Proceso hijo")
Pid = os.fork()
print(f"Estado{Pid}")
if Pid == 0:
  print("Soy el hijo")
  print(f"[Hijo] PID{os.getpid}")
  print(f"[Padre] PPID{os.getppid}")
  print(f"  [Hijo] Mostrando mi PCB...")
  MostrarPCB(os.getpid(), "Hijo")

  sys.exit(0) #Provoca que el proceso muera
else:
  print(f"[Padre] soy el padre de {Pid}")

os.waitpid(Pid,0) #cosecha al hijo y libera la PCB

"""#Ejercicio 2 - Proceso zombie"""

import os
import sys
import time

def MostrarEstado(Pid, Etiqueta):
  with open(f"/proc/{Pid}/status") as F:
    for Linea in F:
      if Linea.startswith("state"):
        print(f" [{Etiqueta}] {Linea.strip()}")
Pid = os.fork()

if Pid == 0:
  print(f"[Hijo] PID{os.getpid()}")
  sys.exit(0)

  print("[Padre] durmiendo pro 2s")
  time.sleep(2)
  MostrarEstado(Pid, "Zombie Activo")

"""#Ejercicio 3 Proceso Huerfano"""

import os
import sys
import time


Pid = os.fork()

if Pid == 0:

  PpidInicial = os.getppid()
  print(f"  [Hijo] PID{os.getpid()}")
  print(f"  [Hijo] PPID{PpidInicial}")
  print("[Hijo] Durmiendo, el padre terminara antes que yo")
  time.sleep(2)

  PpidFinal = os.getppid()

  print(f"[Hijo] Mi padre ya no existe{PpidInicial}")
  print(f"[Hijo] Mi padrastro es{PpidFinal}")
  sys.exit(0)
